### ISSUE TITLE
A new extension to send plain chat message to peer

### ISSUE THREAD

**Issue by vairabagni** [fisch0920/ut_pex#4] opened 2015-07-06 11:57 UTC
How can I use this extension or [ut_metadata](https://github.com/feross/ut_metadata) or by creating a new one to be able to send messages to other peer (chat message) ?

I just started by creating a new extension which i am thinking of integrating that into webtorrent. So I modified torrent.js (inside webtorrent, ln 463) - _onWire callback - this block is same as that of ut_pex.

```Javascript
if (typeof ut_message === 'function') {
    wire.use(ut_message())

    //wire.ut_message.start() // TODO two-way communication
    wire.ut_message.on('peer', function (peer) {
      debug('ut_message: got peer: %s (from %s)', peer, addr)
      self.addPeer(peer)
    })

    wire.ut_message.on('dropped', function (peer) {
      // the remote peer believes a given peer has been dropped from the swarm.
      // if we're not currently connected to it, then remove it from the swarm's queue.
      debug('ut_message: dropped peer: %s (from %s)', peer, addr)
      var peerObj = self.swarm._peers[peer]
      if (!peerObj || !peerObj.conn) self.swarm.removePeer(peer)
    })
  }

```

Is it required? Or i can just use any extension (ut_metadata, ut_pex or mine - ut_message) as:

```Javascript
torrent.swarm.on("wire", function(wire) {
	console.log("onwire - " + wire.peerId + " - " + wire.remoteAddress + ':' + wire.remotePort);
		
	wire.on('extended', function (ext, obj) {
		console.log('extended', ext, obj.toString());
	});
	wire.use(ut_message()); 
        //or
        wire.use(ut_metadata());
        //or
	wire.use(ut_pex()); 
		
	wire.extended(3, 'hello'); //first param will be either 1, 2 or 3
});
```

**Comment by feross** [comment] 2015-07-06 23:04
Duplicate of https://github.com/feross/webtorrent/issues/368

**Comment by fisch0920** [comment] 2016-01-01 16:31
Closing as question is handled in duplicate thread.

**Closed by fisch0920** 2016-01-01 16:31 UTC
